### PR TITLE
Add support for inline attachments

### PR DESCRIPTION
**Pull request by agustintorres**

### CODE REVIEW

**Comment by domodwyer** [comment]
Hi @agustintorres,

**Thanks so much** for the contribution - inline attachments is definitely a big bonus! 

Would you mind covering the inline attachment code path in tests? Ideally using the public API (by calling `AttachInline()` rather than manually adding a `[]attachment{}` in the test code) - the current tests use the `[]attachment{}` way, but I think it'll be better to use the public API after this PR adds other `Attach*` methods - I don't mind changing the existing tests later!

Again **thanks** for the PR :)

**Comment by agustintorres** [comment]
Hi @domodwyer,

Thanks for your prompt response. I don't mind adding a few tests using the existing test patterns. But it's not immediately clear to me how to write new tests that call the Attach*() method directly. The current tests use a "testPartCreator" that can be passed to the "writeAttachments()" function and used to compare the expected results against the actual ones. If the tests were to call Attach*() directly, then it seems to me I'd have to examine  the body of the produced email and look for the attachments in the body, which seems to me like it would require some more infrastructure. Is it fine if I add tests following the current pattern and you can then refactor all of them to call Attach*() directly?

Thanks,
Agustin

**Comment by domodwyer** [comment]
Hi Agustin,

Sounds like a good idea - I'm on holiday right now so not looked into it properly.

Thanks for the help!

**Comment by agustintorres** [comment]
I added some tests for inline attachments. I'll let you possibly refactor the tests as you prefer. Sorry for the messy commit log -- I'm hoping you can just squash the commits on your end.

Would be nice if you can merge this soon since I'm using your project and if it takes a while then I'll have to use my own fork in the meantime.

**Comment by domodwyer** [comment]
Merged!

Thanks so much for taking the time to share your changes :)

Dom

**Comment by agustintorres** [comment]
Great! Thank you!

**Pull request merged**
