### PR TITLE
added CC support

### PR DESCRIPTION
**Pull request by Raz0rwire**
I've been using your package for the MimeBuf function to use with the SES RawMessage API (mainly for attachments) but I've found that it was lacking an implementation of CC's. I'm hoping you'll accept this PR because I would like to keep using your package in production!

### CODE REVIEW

**Comment by domodwyer** [comment]
Hi @Raz0rwire,

**Thank your** for your contribution! I'm happy to merge it if you can include some tests, specifically something like [TestMailYakWriteHeaders](https://github.com/domodwyer/mailyak/blob/master/mime_test.go#L58) in `mime_test.go` that ensures the CC headers are created properly - I can see from your code it'll be fine, but it's more a safety net for future work. It seems the tests for Bcc are missing too, but I'm happy to add them.

If you're not too sure about testing I can help, just retarget your PR to the development branch :)

Thanks again - glad you like it!

**Comment by Raz0rwire** [comment]
I'll do that later today!

**Comment by Raz0rwire** [comment]
Tests are added (for cc's and bcc's), let me know if you want any other improvements / changes

**Comment by domodwyer** [comment]
Fantastic!

Thanks so much for the contribution, it really is appreciated!

**Pull request merged**
